name: Publiser

on: push

jobs:
  conditional_job_check_files:
    name: Finn endringer i tokens.json
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        $diff = git diff --name-only HEAD^ HEAD
        $SourceDiff = $diff | Where-Object { $_ -match '^tokens.json$' }
        $HasDiff = $SourceDiff.Length -gt 0
        Write-Host "::set-output name=docs_changed::$HasDiff"

  publiser:
    name: Publiser ny versjon
    runs-on: ubuntu-latest
    needs: [ conditional_job_check_files ]
    if: needs.conditional_job_check_files.outputs.docs_changed == 'True'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
      - run: npm run set-version-to-latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: contains(fromJson('["major", "minor", "patch"]'), github.event.head_commit.message)
        run: npm version --no-git-tag-version ${{ github.event.head_commit.message }}
      - if: (!contains(fromJson('["major", "minor", "patch"]'), github.event.head_commit.message))
        run: npm version --no-git-tag-version patch
      - run: npm ci
      - run: npm run build
      - run: npm run declare
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}